import { supabase, signInWithEmail, signOut, getCurrentUser, ensureProfile } from './supabase.js';

const grid=document.getElementById('carGrid'),toast=document.getElementById('toast');let activeFilter='all',query='',cloudCars=[];
const favorites=new Set(JSON.parse(localStorage.getItem('bigexFavorites')||'[]')),compare=new Set();
function normalizeCloud(c){return {...c,price:'₦'+Number(c.price||0).toLocaleString(),spec:(c.fuel||'')+' • '+(c.transmission||'Automatic'),mileage:Number(c.mileage||0).toLocaleString()+' km',symbol:'◇',image:c.image_url||''}}
async function loadCloudListings(){const {data,error}=await supabase.from('listings').select('*').eq('status','approved').order('created_at',{ascending:false});if(error){console.warn('Supabase listings unavailable:',error.message);showToast('Could not load marketplace listings');return}cloudCars=(data||[]).map(normalizeCloud);render()}
function allCars(){return cloudCars}
function render(){const cars=allCars(),list=cars.filter(c=>(activeFilter==='all'||c.type===activeFilter)&&(!query||[c.name,c.type,c.fuel,c.location].join(' ').toLowerCase().includes(query)));grid.innerHTML=list.map(c=>'<article class="listing"><div class="listing-img">'+(c.image?'<img src="'+c.image+'" alt="'+c.name+'" loading="lazy" referrerpolicy="no-referrer">':c.symbol)+'</div><div class="listing-body"><div class="listing-meta"><span>'+c.year+' • '+c.type+'</span><span>'+c.location+'</span></div><h3>'+c.name+'</h3><div class="listing-bottom"><div><div class="listing-price">'+c.price+'</div><small style="color:#6f7b89">'+c.spec+' • '+c.mileage+'</small></div><div style="display:flex;gap:7px"><button class="heart" aria-label="Save '+c.name+'" data-heart="'+c.id+'">'+(favorites.has(c.id)?'♥':'♡')+'</button><button class="heart" aria-label="Compare '+c.name+'" data-compare="'+c.id+'">'+(compare.has(c.id)?'✓':'+')+'</button></div></div></div></article>').join('')||'<p style="color:#8d98a8">No cars match those filters.</p>';document.querySelectorAll('[data-heart]').forEach(b=>b.onclick=()=>{const id=b.dataset.heart;favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('bigexFavorites',JSON.stringify([...favorites]));render();showToast(favorites.has(id)?'Saved to your shortlist':'Removed from shortlist')});document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{const id=b.dataset.compare;if(compare.has(id))compare.delete(id);else if(compare.size<4)compare.add(id);else return showToast('Compare up to 4 cars');render();showToast(compare.size?compare.size+' car'+(compare.size>1?'s':'')+' selected for comparison':'Comparison cleared')})}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
function doSearch(v){query=v.trim().toLowerCase();render();document.getElementById('explore').scrollIntoView({behavior:'smooth'});showToast('Marketplace updated')}
document.getElementById('searchBtn').onclick=()=>doSearch(document.getElementById('heroSearch').value);document.getElementById('heroSearch').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch(e.target.value)});document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{document.getElementById('heroSearch').value=b.dataset.search;doSearch(b.dataset.search)});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()});document.getElementById('viewAll').onclick=()=>{activeFilter='all';query='';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));document.getElementById('heroSearch').value='';render();document.getElementById('explore').scrollIntoView({behavior:'smooth'})};
document.getElementById('loginBtn').onclick=async()=>{try{const user=await getCurrentUser();if(user){await signOut();localStorage.removeItem('bigexSession');showToast('Signed out');return}const email=prompt('Enter your email. Supabase will send you a secure sign-in link.');if(!email)return;await signInWithEmail(email);showToast('Check your email for the secure sign-in link')}catch(error){showToast(error.message||'Sign-in failed')}};
document.getElementById('sellBtn').onclick=()=>location.href='sell.html';
document.getElementById('aiBtn').onclick=()=>{const input=document.getElementById('aiInput'),reply=document.getElementById('aiReply'),text=input.value.trim().toLowerCase();if(!text){reply.textContent='Try a budget, body type, location, or fuel preference.';return}const s=allCars().filter(c=>text.includes(c.type.toLowerCase())||text.includes(c.fuel.toLowerCase())||text.includes(c.location.toLowerCase())||text.includes(c.name.split(' ')[0].toLowerCase()));reply.textContent=s.length?'Possible matches: '+s.map(c=>c.name).join(', ')+'.':'Try mentioning SUV, Sedan, Electric, Lagos, Toyota, BMW, or another preference.'};
supabase.auth.onAuthStateChange(async(event,session)=>{if(session?.user){try{const profile=await ensureProfile(session.user);localStorage.setItem('bigexSession',JSON.stringify({id:session.user.id,email:session.user.email,role:profile?.role||'buyer'}));if(profile?.role==='admin')setTimeout(()=>location.href='admin.html',300);else showToast('Signed in successfully')}catch(error){console.error(error);showToast('Signed in, but profile setup needs attention')}}});
render();loadCloudListings();