const cars=[
{id:'BC001',name:'Toyota Land Cruiser',year:2023,type:'SUV',fuel:'Petrol',price:'₦82.0M',spec:'3.5L • 409 HP',mileage:'18,400 km',location:'Lagos',symbol:'◆'},
{id:'BC002',name:'Lexus RX 350',year:2024,type:'SUV',fuel:'Petrol',price:'₦67.5M',spec:'2.4L Turbo • 275 HP',mileage:'8,200 km',location:'Abuja',symbol:'◇'},
{id:'BC003',name:'BMW M4 Competition',year:2024,type:'Coupe',fuel:'Petrol',price:'₦95.0M',spec:'3.0L • 503 HP',mileage:'4,600 km',location:'Lagos',symbol:'▰'},
{id:'BC004',name:'Mercedes C300',year:2023,type:'Sedan',fuel:'Petrol',price:'₦58.0M',spec:'2.0L Turbo • 255 HP',mileage:'21,000 km',location:'Port Harcourt',symbol:'◈'},
{id:'BC005',name:'Tesla Model 3',year:2024,type:'Electric',fuel:'Electric',price:'₦72.0M',spec:'Dual Motor • 394 HP',mileage:'5,100 km',location:'Lagos',symbol:'⚡'},
{id:'BC006',name:'Range Rover Sport',year:2022,type:'SUV',fuel:'Petrol',price:'₦115.0M',spec:'3.0L • 355 HP',mileage:'31,200 km',location:'Lagos',symbol:'▰'}
];
const grid=document.getElementById('carGrid'),toast=document.getElementById('toast');let activeFilter='all',query='';const favorites=new Set(JSON.parse(localStorage.getItem('bigexFavorites')||'[]'));const compare=new Set();
function render(){const list=cars.filter(c=>(activeFilter==='all'||c.type===activeFilter)&&(!query||`${c.name} ${c.type} ${c.fuel} ${c.location}`.toLowerCase().includes(query)));grid.innerHTML=list.map(c=>`<article class="listing"><div class="listing-img">${c.symbol}</div><div class="listing-body"><div class="listing-meta"><span>${c.year} • ${c.type}</span><span>${c.location}</span></div><h3>${c.name}</h3><div class="listing-bottom"><div><div class="listing-price">${c.price}</div><small style="color:#6f7b89">${c.spec} • ${c.mileage}</small></div><div style="display:flex;gap:7px"><button class="heart" aria-label="Save ${c.name}" data-heart="${c.id}">${favorites.has(c.id)?'♥':'♡'}</button><button class="heart" aria-label="Compare ${c.name}" data-compare="${c.id}">${compare.has(c.id)?'✓':'+'}</button></div></div></div></article>`).join('')||'<p style="color:#8d98a8">No cars match those filters.</p>';document.querySelectorAll('[data-heart]').forEach(b=>b.onclick=()=>{const id=b.dataset.heart;favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('bigexFavorites',JSON.stringify([...favorites]));render();showToast(favorites.has(id)?'Saved to your shortlist':'Removed from shortlist')});document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{const id=b.dataset.compare;if(compare.has(id))compare.delete(id);else if(compare.size<4)compare.add(id);else return showToast('Compare up to 4 cars');render();showToast(compare.size?`${compare.size} car${compare.size>1?'s':''} selected for comparison`:'Comparison cleared')})}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
function doSearch(v){query=v.trim().toLowerCase();render();document.getElementById('explore').scrollIntoView({behavior:'smooth'});showToast('Marketplace updated')}
document.getElementById('searchBtn').onclick=()=>doSearch(document.getElementById('heroSearch').value);document.getElementById('heroSearch').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch(e.target.value)});document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{document.getElementById('heroSearch').value=b.dataset.search;doSearch(b.dataset.search)});
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()});document.getElementById('viewAll').onclick=()=>{activeFilter='all';query='';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));document.getElementById('heroSearch').value='';render();document.getElementById('explore').scrollIntoView({behavior:'smooth'})};
document.getElementById('loginBtn').onclick=()=>{const email=prompt('Enter your Gmail address');if(!email)return;const normalized=email.trim().toLowerCase(),role=normalized==='igetobiloluwa36@gmail.com'?'admin':'buyer';localStorage.setItem('bigexSession',JSON.stringify({email:email.trim(),role,signedInAt:new Date().toISOString()}));showToast(role==='admin'?'Administrator recognized':'Account signed in');if(role==='admin')setTimeout(()=>location.href='admin.html',500)};
document.getElementById('sellBtn').onclick=()=>showToast('Seller onboarding is ready for backend connection.');document.getElementById('aiBtn').onclick=()=>{const input=document.getElementById('aiInput'),reply=document.getElementById('aiReply'),text=input.value.trim().toLowerCase();if(!text){reply.textContent='Try a budget, body type, location, or fuel preference.';return}const s=cars.filter(c=>text.includes(c.type.toLowerCase())||text.includes(c.fuel.toLowerCase())||text.includes(c.location.toLowerCase())||text.includes(c.name.split(' ')[0].toLowerCase()));reply.textContent=s.length?`Possible matches: ${s.map(c=>c.name).join(', ')}.`:'Try mentioning SUV, Sedan, Electric, Lagos, Toyota, BMW, or another preference.'};render();